DROP TABLE IF EXISTS public.PuiStoUserAccount CASCADE;
DROP SEQUENCE IF EXISTS PuiStoUserSeq;

DROP TABLE IF EXISTS public.PuiStoStorageTable CASCADE;
DROP SEQUENCE IF EXISTS PuiStoStorageSeq;

DROP TABLE IF EXISTS public.tokensession CASCADE;

DROP TABLE IF EXISTS public. CASCADE;